#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${MENTAT_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
CONFIG_DIR="${MENTAT_CONFIG_DIR:-$HOME/.config/mentat}"
ENV_FILE="$CONFIG_DIR/env"
PID_FILE="$CONFIG_DIR/gateway.pid"
LOG_FILE="$CONFIG_DIR/gateway.log"
BIN_PATH="${MENTAT_BIN_PATH:-$HOME/.local/bin/mentat}"
BROKER_SHUTDOWN_SCRIPT="$ROOT_DIR/scripts/mentat/broker_shutdown.py"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true

load_env() {
  if [[ -f "$ENV_FILE" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
  fi
}

broker_state_dir() {
  printf '%s' "${MENTAT_STATE_DIR:-$CONFIG_DIR/state}"
}

broker_data_dir() {
  printf '%s' "${MENTAT_BROKER_DATA_DIR:-$CONFIG_DIR/broker}"
}

find_pnpm() {
  if command -v pnpm >/dev/null 2>&1; then
    command -v pnpm
  elif [[ -x "$HOME/.local/bin/pnpm" ]]; then
    printf '%s\n' "$HOME/.local/bin/pnpm"
  else
    echo "pnpm is not installed. Run: bash install.sh" >&2
    return 1
  fi
}

find_python() {
  if command -v python3 >/dev/null 2>&1; then
    command -v python3
  elif command -v python >/dev/null 2>&1; then
    command -v python
  else
    echo "Python 3.11 or newer is required." >&2
    return 1
  fi
}

run_pnpm() {
  local pnpm_bin
  pnpm_bin="$(find_pnpm)"
  (cd "$ROOT_DIR" && "$pnpm_bin" "$@")
}

run_openclaw() {
  run_pnpm openclaw "$@"
}

write_setting() {
  local name="$1"
  local value="$2"
  printf '%s=%q\n' "$name" "$value"
}

save_config() {
  local provider="$1"
  local base_url="${2:-}"
  local api_key="${3:-}"
  local model_id="${4:-moonshotai/Kimi-K2.7-Code}"
  local template_hash="${5:-}"
  local gateway_port="${MENTAT_GATEWAY_PORT:-18789}"
  local broker_port="${MENTAT_BROKER_PORT:-18890}"
  local ollama_model="${MENTAT_OLLAMA_MODEL:-kimi-k2.7-code:cloud}"

  umask 077
  {
    printf '# Generated by mentat setup. Keep this file private.\n'
    write_setting MENTAT_PROVIDER "$provider"
    write_setting MENTAT_VLLM_BASE_URL "$base_url"
    if [[ -n "$api_key" ]]; then
      write_setting VAST_API_KEY "$api_key"
    fi
    write_setting MENTAT_MODEL_ID "$model_id"
    write_setting VAST_TEMPLATE_HASH "$template_hash"
    write_setting MENTAT_GATEWAY_PORT "$gateway_port"
    write_setting MENTAT_BROKER_PORT "$broker_port"
    write_setting MENTAT_MAX_HOURLY_USD "${MENTAT_MAX_HOURLY_USD:-32}"
    write_setting MENTAT_MAX_SESSION_HOURS "${MENTAT_MAX_SESSION_HOURS:-4}"
    write_setting MENTAT_MAX_ACTIVE_PAID_SESSIONS "${MENTAT_MAX_ACTIVE_PAID_SESSIONS:-1}"
    write_setting MENTAT_PRODUCTION_MODE "${MENTAT_PRODUCTION_MODE:-1}"
    write_setting MENTAT_OLLAMA_MODEL "$ollama_model"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

prompt_value() {
  local label="$1"
  local current="${2:-}"
  local answer=""
  if [[ -n "$current" ]]; then
    read -r -p "$label [$current]: " answer
    printf '%s' "${answer:-$current}"
  else
    read -r -p "$label: " answer
    printf '%s' "$answer"
  fi
}

setup_vast() {
  load_env
  local base_url="${MENTAT_VLLM_BASE_URL:-https://openai.vast.ai/mentat-kimi-k2-7-code/v1}"
  local api_key="${VAST_API_KEY:-}"
  local model_id="moonshotai/Kimi-K2.7-Code"
  local template_hash="${VAST_TEMPLATE_HASH:-}"

  if [[ -t 0 ]]; then
    base_url="$(prompt_value 'Kimi endpoint identity (created only after approval)' "$base_url")"
    template_hash="$(prompt_value 'Vast Serverless template hash (optional until endpoint creation)' "$template_hash")"
    if [[ -z "$api_key" ]]; then
      read -r -s -p "Vast API key: " api_key
      printf '\n'
    else
      read -r -s -p "Vast API key [press Enter to keep saved key]: " new_key
      printf '\n'
      api_key="${new_key:-$api_key}"
    fi
  fi

  [[ -n "$base_url" ]] || { echo "A Kimi endpoint identity is required." >&2; return 1; }
  [[ -n "$api_key" ]] || { echo "A Vast API key is required." >&2; return 1; }

  base_url="${base_url%/}"
  if [[ "$base_url" != */v1 ]]; then
    base_url="$base_url/v1"
  fi

  save_config vast "$base_url" "$api_key" "$model_id" "$template_hash"
  load_env
  echo "Configuring the local OpenClaw provider and production sandbox..."
  MENTAT_CONFIG_ONLY=1 bash "$ROOT_DIR/scripts/mentat/launch.sh"
  echo "Mentat broker is configured. No paid endpoint was started."
}

setup_ollama() {
  command -v ollama >/dev/null 2>&1 || {
    echo "Ollama is not installed. Install Ollama, then rerun: mentat setup ollama-cloud" >&2
    return 1
  }
  load_env
  save_config ollama-cloud "" "" "${MENTAT_MODEL_ID:-moonshotai/Kimi-K2.7-Code}" "${VAST_TEMPLATE_HASH:-}"
  echo "Ollama Cloud is selected."
  echo "Run 'ollama signin' if this computer is not already signed in."
}

command_setup() {
  load_env
  local provider="${1:-${MENTAT_PROVIDER:-}}"
  if [[ -z "$provider" ]] && [[ -t 0 ]]; then
    echo "Choose Mentat's inference provider:"
    echo "  1) Mentat broker with guarded Vast.ai compute"
    echo "  2) Ollama Cloud (fallback)"
    read -r -p "Selection [1]: " selection
    case "${selection:-1}" in
      1) provider=vast ;;
      2) provider=ollama-cloud ;;
      *) echo "Invalid selection." >&2; return 2 ;;
    esac
  fi
  provider="${provider:-vast}"

  case "$provider" in
    vast) setup_vast ;;
    ollama|ollama-cloud) setup_ollama ;;
    *) echo "Unknown provider: $provider" >&2; return 2 ;;
  esac
}

pid_is_running() {
  [[ -f "$PID_FILE" ]] || return 1
  local pid
  pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null
}

broker_pid_is_running() {
  local pid_file
  pid_file="$(broker_data_dir)/broker.pid"
  [[ -f "$pid_file" ]] || return 1
  local pid
  pid="$(cat "$pid_file" 2>/dev/null || true)"
  [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null
}

stop_broker_gracefully() {
  load_env
  [[ "${MENTAT_PROVIDER:-vast}" == "vast" ]] || return 0
  local python_bin state_dir data_dir
  python_bin="$(find_python)"
  state_dir="$(broker_state_dir)"
  data_dir="$(broker_data_dir)"
  mkdir -p "$state_dir" "$data_dir"
  "$python_bin" "$BROKER_SHUTDOWN_SCRIPT" \
    --port "${MENTAT_BROKER_PORT:-18890}" \
    --token-file "$state_dir/broker-admin.token" \
    --pid-file "$data_dir/broker.pid" \
    --timeout 120
}

command_start() {
  load_env
  if [[ ! -f "$ENV_FILE" ]]; then
    command_setup
    load_env
  fi

  if [[ "${1:-}" == "--foreground" ]]; then
    exec bash "$ROOT_DIR/scripts/mentat/launch.sh"
  fi

  if [[ "${MENTAT_PROVIDER:-vast}" == "ollama-cloud" ]]; then
    echo "Ollama Cloud launch is interactive; starting in the foreground."
    exec bash "$ROOT_DIR/scripts/mentat/launch.sh"
  fi

  if pid_is_running; then
    echo "Mentat is already running with PID $(cat "$PID_FILE")."
    return 0
  fi

  : > "$LOG_FILE"
  nohup bash "$ROOT_DIR/scripts/mentat/launch.sh" >> "$LOG_FILE" 2>&1 &
  local pid=$!
  printf '%s\n' "$pid" > "$PID_FILE"
  chmod 600 "$PID_FILE"

  sleep 2
  if kill -0 "$pid" 2>/dev/null; then
    echo "Mentat started in the background (PID $pid)."
    echo "Logs: $LOG_FILE"
  else
    echo "Mentat exited during startup. Recent logs:" >&2
    tail -n 40 "$LOG_FILE" >&2 || true
    rm -f "$PID_FILE"
    return 1
  fi
}

command_stop() {
  load_env
  local broker_stopped=1
  if ! stop_broker_gracefully >/dev/null; then
    broker_stopped=0
    echo "Warning: graceful broker shutdown failed; forced cleanup will follow." >&2
  fi
  run_openclaw gateway stop >/dev/null 2>&1 || true
  if pid_is_running; then
    local pid
    pid="$(cat "$PID_FILE")"
    kill "$pid" 2>/dev/null || true
    for _ in 1 2 3 4 5; do
      kill -0 "$pid" 2>/dev/null || break
      sleep 1
    done
    kill -9 "$pid" 2>/dev/null || true
  fi
  rm -f "$PID_FILE" "$(broker_state_dir)/broker-admin.token"
  if [[ "$broker_stopped" -eq 1 ]]; then
    echo "Mentat broker cooled and stopped cleanly."
  else
    echo "Verify Vast has zero warm workers." >&2
  fi
  echo "Mentat stopped."
}

command_status() {
  load_env
  if pid_is_running; then
    echo "Mentat process: running (PID $(cat "$PID_FILE"))"
  else
    echo "Mentat process: not running through the local wrapper"
    rm -f "$PID_FILE" 2>/dev/null || true
  fi
  if broker_pid_is_running; then
    echo "Broker process: running (PID $(cat "$(broker_data_dir)/broker.pid"))"
  else
    echo "Broker process: not running"
    rm -f "$(broker_data_dir)/broker.pid" 2>/dev/null || true
  fi
  echo "Provider: ${MENTAT_PROVIDER:-not configured}"
  echo "Gateway port: ${MENTAT_GATEWAY_PORT:-18789}"
  run_openclaw gateway status || true
}

command_chat() {
  if [[ "$#" -gt 0 ]]; then
    run_openclaw agent --message "$*" --thinking high
  else
    run_pnpm tui
  fi
}

command_logs() {
  touch "$LOG_FILE"
  tail -n "${MENTAT_LOG_LINES:-80}" -f "$LOG_FILE"
}

command_vast() {
  load_env
  exec "$(find_python)" "$ROOT_DIR/scripts/mentat/vast_endpoint.py" "$@"
}

command_config() {
  local action="${1:-path}"
  case "$action" in
    path)
      echo "$ENV_FILE"
      ;;
    show)
      if [[ ! -f "$ENV_FILE" ]]; then
        echo "No configuration exists. Run: mentat setup" >&2
        return 1
      fi
      sed -E 's/^(VAST_API_KEY|.*TOKEN|.*SECRET)=.*/\1=*** redacted ***/' "$ENV_FILE"
      ;;
    edit)
      "${EDITOR:-vi}" "$ENV_FILE"
      ;;
    reset)
      rm -f "$ENV_FILE"
      echo "Mentat configuration removed. Run: mentat setup"
      ;;
    *)
      echo "Usage: mentat config [path|show|edit|reset]" >&2
      return 2
      ;;
  esac
}

command_doctor() {
  bash "$ROOT_DIR/scripts/mentat/doctor.sh" "$@"
}

command_update() {
  if [[ -n "$(git -C "$ROOT_DIR" status --porcelain)" ]]; then
    echo "The Mentat checkout has uncommitted changes. Commit or stash them before updating." >&2
    return 1
  fi
  git -C "$ROOT_DIR" pull --ff-only
  run_pnpm install
  run_pnpm ui:build
  echo "Mentat is updated. Run 'mentat doctor' to verify it."
}

command_uninstall() {
  local purge=0
  [[ "${1:-}" == "--purge" ]] && purge=1
  command_stop || true
  rm -f "$BIN_PATH"
  if [[ "$purge" -eq 1 ]]; then
    rm -rf "$CONFIG_DIR"
    echo "Mentat command, configuration, and local state removed."
  else
    echo "Mentat command removed. Configuration was kept at $CONFIG_DIR"
  fi
  echo "The source checkout was not deleted: $ROOT_DIR"
}

command_version() {
  local version commit
  version="$(node -p "require('$ROOT_DIR/package.json').version")"
  commit="$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  echo "Mentat $version ($commit)"
}

show_help() {
  cat <<'EOF'
Mentat — local AI control plane with guarded Vast inference

Usage:
  mentat <command> [options]

First run:
  mentat doctor
  mentat setup [vast|ollama-cloud]
  mentat start
  mentat chat

Everyday commands:
  mentat start [--foreground]
  mentat stop
  mentat restart
  mentat status
  mentat chat [message]
  mentat logs
  mentat config [path|show|edit|reset]
  mentat doctor
  mentat update

Vast endpoint commands:
  mentat vast estimate --hourly-price 28 --hours 2
  mentat vast create --accept-test-worker-cost
  mentat vast status
  mentat vast test
  mentat vast warm
  mentat vast cool
  mentat vast destroy --confirm

Maintenance:
  mentat version
  mentat uninstall [--purge]
  mentat help
EOF
}

command="${1:-help}"
shift || true

case "$command" in
  setup) command_setup "$@" ;;
  start) command_start "$@" ;;
  foreground) command_start --foreground ;;
  stop) command_stop ;;
  restart) command_stop; command_start ;;
  status) command_status ;;
  chat) command_chat "$@" ;;
  logs) command_logs ;;
  vast) command_vast "$@" ;;
  config) command_config "$@" ;;
  doctor) command_doctor "$@" ;;
  update) command_update ;;
  uninstall) command_uninstall "$@" ;;
  version) command_version ;;
  help|-h|--help) show_help ;;
  *) echo "Unknown command: $command" >&2; show_help >&2; exit 2 ;;
esac
